backend = "fastresize"
color_space = "lch"
palette = "dark"

[templates]
# This tells wallust to generate pywal-compatible files
waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors-wallust.css'
hypr.template = 'colors-hypr.conf'
hypr.target = '~/.config/hypr/themes/wallust.conf'
